# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CD_RECYCLE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CD_RECYCLE

pod 'NMapsMap'
pod 'Alamofire', '~>5.0'

  target 'CD_RECYCLETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CD_RECYCLEUITests' do
    # Pods for testing
  end

end
